/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_PAcademico service. Represents a row in the &quot;AulaVirtual_T_Ul_PAcademico&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_PAcademicoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_PAcademicoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_PAcademico
 * @generated
 */
@ProviderType
public interface T_Ul_PAcademicoModel
	extends BaseModel<T_Ul_PAcademico>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_p academico model instance should use the {@link T_Ul_PAcademico} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_p academico.
	 *
	 * @return the primary key of this t_ ul_p academico
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_p academico.
	 *
	 * @param primaryKey the primary key of this t_ ul_p academico
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_p academico.
	 *
	 * @return the uuid of this t_ ul_p academico
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_p academico.
	 *
	 * @param uuid the uuid of this t_ ul_p academico
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id periodo of this t_ ul_p academico.
	 *
	 * @return the id periodo of this t_ ul_p academico
	 */
	public long getIdPeriodo();

	/**
	 * Sets the id periodo of this t_ ul_p academico.
	 *
	 * @param idPeriodo the id periodo of this t_ ul_p academico
	 */
	public void setIdPeriodo(long idPeriodo);

	/**
	 * Returns the titulo periodo of this t_ ul_p academico.
	 *
	 * @return the titulo periodo of this t_ ul_p academico
	 */
	@AutoEscape
	public String getTituloPeriodo();

	/**
	 * Sets the titulo periodo of this t_ ul_p academico.
	 *
	 * @param tituloPeriodo the titulo periodo of this t_ ul_p academico
	 */
	public void setTituloPeriodo(String tituloPeriodo);

	/**
	 * Returns the f inicio periodo of this t_ ul_p academico.
	 *
	 * @return the f inicio periodo of this t_ ul_p academico
	 */
	public Date getFInicioPeriodo();

	/**
	 * Sets the f inicio periodo of this t_ ul_p academico.
	 *
	 * @param fInicioPeriodo the f inicio periodo of this t_ ul_p academico
	 */
	public void setFInicioPeriodo(Date fInicioPeriodo);

	/**
	 * Returns the f fin periodo of this t_ ul_p academico.
	 *
	 * @return the f fin periodo of this t_ ul_p academico
	 */
	public Date getFFinPeriodo();

	/**
	 * Sets the f fin periodo of this t_ ul_p academico.
	 *
	 * @param fFinPeriodo the f fin periodo of this t_ ul_p academico
	 */
	public void setFFinPeriodo(Date fFinPeriodo);

	/**
	 * Returns the porc periodo of this t_ ul_p academico.
	 *
	 * @return the porc periodo of this t_ ul_p academico
	 */
	@AutoEscape
	public String getPorcPeriodo();

	/**
	 * Sets the porc periodo of this t_ ul_p academico.
	 *
	 * @param porcPeriodo the porc periodo of this t_ ul_p academico
	 */
	public void setPorcPeriodo(String porcPeriodo);

	/**
	 * Returns the t_ ul_ curso_id of this t_ ul_p academico.
	 *
	 * @return the t_ ul_ curso_id of this t_ ul_p academico
	 */
	public long getT_Ul_Curso_id();

	/**
	 * Sets the t_ ul_ curso_id of this t_ ul_p academico.
	 *
	 * @param T_Ul_Curso_id the t_ ul_ curso_id of this t_ ul_p academico
	 */
	public void setT_Ul_Curso_id(long T_Ul_Curso_id);

	/**
	 * Returns the group ID of this t_ ul_p academico.
	 *
	 * @return the group ID of this t_ ul_p academico
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_p academico.
	 *
	 * @param groupId the group ID of this t_ ul_p academico
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_p academico.
	 *
	 * @return the company ID of this t_ ul_p academico
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_p academico.
	 *
	 * @param companyId the company ID of this t_ ul_p academico
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_p academico.
	 *
	 * @return the user ID of this t_ ul_p academico
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_p academico.
	 *
	 * @param userId the user ID of this t_ ul_p academico
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_p academico.
	 *
	 * @return the user uuid of this t_ ul_p academico
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_p academico.
	 *
	 * @param userUuid the user uuid of this t_ ul_p academico
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_p academico.
	 *
	 * @return the user name of this t_ ul_p academico
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_p academico.
	 *
	 * @param userName the user name of this t_ ul_p academico
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_p academico.
	 *
	 * @return the create date of this t_ ul_p academico
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_p academico.
	 *
	 * @param createDate the create date of this t_ ul_p academico
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_p academico.
	 *
	 * @return the modified date of this t_ ul_p academico
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_p academico.
	 *
	 * @param modifiedDate the modified date of this t_ ul_p academico
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}