/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_Actividad service. Represents a row in the &quot;AulaVirtual_T_Ul_Actividad&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_ActividadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_ActividadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_Actividad
 * @generated
 */
@ProviderType
public interface T_Ul_ActividadModel
	extends BaseModel<T_Ul_Actividad>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ actividad model instance should use the {@link T_Ul_Actividad} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ actividad.
	 *
	 * @return the primary key of this t_ ul_ actividad
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ actividad.
	 *
	 * @param primaryKey the primary key of this t_ ul_ actividad
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ actividad.
	 *
	 * @return the uuid of this t_ ul_ actividad
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ actividad.
	 *
	 * @param uuid the uuid of this t_ ul_ actividad
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id actividad of this t_ ul_ actividad.
	 *
	 * @return the id actividad of this t_ ul_ actividad
	 */
	public long getIdActividad();

	/**
	 * Sets the id actividad of this t_ ul_ actividad.
	 *
	 * @param idActividad the id actividad of this t_ ul_ actividad
	 */
	public void setIdActividad(long idActividad);

	/**
	 * Returns the titulo actividad of this t_ ul_ actividad.
	 *
	 * @return the titulo actividad of this t_ ul_ actividad
	 */
	@AutoEscape
	public String getTituloActividad();

	/**
	 * Sets the titulo actividad of this t_ ul_ actividad.
	 *
	 * @param tituloActividad the titulo actividad of this t_ ul_ actividad
	 */
	public void setTituloActividad(String tituloActividad);

	/**
	 * Returns the tipo actividad of this t_ ul_ actividad.
	 *
	 * @return the tipo actividad of this t_ ul_ actividad
	 */
	@AutoEscape
	public String getTipoActividad();

	/**
	 * Sets the tipo actividad of this t_ ul_ actividad.
	 *
	 * @param tipoActividad the tipo actividad of this t_ ul_ actividad
	 */
	public void setTipoActividad(String tipoActividad);

	/**
	 * Returns the descri actividad of this t_ ul_ actividad.
	 *
	 * @return the descri actividad of this t_ ul_ actividad
	 */
	@AutoEscape
	public String getDescriActividad();

	/**
	 * Sets the descri actividad of this t_ ul_ actividad.
	 *
	 * @param descriActividad the descri actividad of this t_ ul_ actividad
	 */
	public void setDescriActividad(String descriActividad);

	/**
	 * Returns the estado entr actividad of this t_ ul_ actividad.
	 *
	 * @return the estado entr actividad of this t_ ul_ actividad
	 */
	@AutoEscape
	public String getEstadoEntrActividad();

	/**
	 * Sets the estado entr actividad of this t_ ul_ actividad.
	 *
	 * @param estadoEntrActividad the estado entr actividad of this t_ ul_ actividad
	 */
	public void setEstadoEntrActividad(String estadoEntrActividad);

	/**
	 * Returns the f creac actividad of this t_ ul_ actividad.
	 *
	 * @return the f creac actividad of this t_ ul_ actividad
	 */
	public Date getFCreacActividad();

	/**
	 * Sets the f creac actividad of this t_ ul_ actividad.
	 *
	 * @param fCreacActividad the f creac actividad of this t_ ul_ actividad
	 */
	public void setFCreacActividad(Date fCreacActividad);

	/**
	 * Returns the f cierr actividad of this t_ ul_ actividad.
	 *
	 * @return the f cierr actividad of this t_ ul_ actividad
	 */
	public Date getFCierrActividad();

	/**
	 * Sets the f cierr actividad of this t_ ul_ actividad.
	 *
	 * @param fCierrActividad the f cierr actividad of this t_ ul_ actividad
	 */
	public void setFCierrActividad(Date fCierrActividad);

	/**
	 * Returns the porc actividad of this t_ ul_ actividad.
	 *
	 * @return the porc actividad of this t_ ul_ actividad
	 */
	@AutoEscape
	public String getPorcActividad();

	/**
	 * Sets the porc actividad of this t_ ul_ actividad.
	 *
	 * @param porcActividad the porc actividad of this t_ ul_ actividad
	 */
	public void setPorcActividad(String porcActividad);

	/**
	 * Returns the t_ ul_ califi_id of this t_ ul_ actividad.
	 *
	 * @return the t_ ul_ califi_id of this t_ ul_ actividad
	 */
	public long getT_Ul_Califi_id();

	/**
	 * Sets the t_ ul_ califi_id of this t_ ul_ actividad.
	 *
	 * @param T_Ul_Califi_id the t_ ul_ califi_id of this t_ ul_ actividad
	 */
	public void setT_Ul_Califi_id(long T_Ul_Califi_id);

	/**
	 * Returns the t_ ul_p academico_id of this t_ ul_ actividad.
	 *
	 * @return the t_ ul_p academico_id of this t_ ul_ actividad
	 */
	public long getT_Ul_PAcademico_id();

	/**
	 * Sets the t_ ul_p academico_id of this t_ ul_ actividad.
	 *
	 * @param T_Ul_PAcademico_id the t_ ul_p academico_id of this t_ ul_ actividad
	 */
	public void setT_Ul_PAcademico_id(long T_Ul_PAcademico_id);

	/**
	 * Returns the group ID of this t_ ul_ actividad.
	 *
	 * @return the group ID of this t_ ul_ actividad
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ actividad.
	 *
	 * @param groupId the group ID of this t_ ul_ actividad
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ actividad.
	 *
	 * @return the company ID of this t_ ul_ actividad
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ actividad.
	 *
	 * @param companyId the company ID of this t_ ul_ actividad
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ actividad.
	 *
	 * @return the user ID of this t_ ul_ actividad
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ actividad.
	 *
	 * @param userId the user ID of this t_ ul_ actividad
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ actividad.
	 *
	 * @return the user uuid of this t_ ul_ actividad
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ actividad.
	 *
	 * @param userUuid the user uuid of this t_ ul_ actividad
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ actividad.
	 *
	 * @return the user name of this t_ ul_ actividad
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ actividad.
	 *
	 * @param userName the user name of this t_ ul_ actividad
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ actividad.
	 *
	 * @return the create date of this t_ ul_ actividad
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ actividad.
	 *
	 * @param createDate the create date of this t_ ul_ actividad
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ actividad.
	 *
	 * @return the modified date of this t_ ul_ actividad
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ actividad.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ actividad
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}