/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_ResEvaluacion service. Represents a row in the &quot;AulaVirtual_T_Ul_ResEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_ResEvaluacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_ResEvaluacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_ResEvaluacion
 * @generated
 */
@ProviderType
public interface T_Ul_ResEvaluacionModel
	extends BaseModel<T_Ul_ResEvaluacion>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ res evaluacion model instance should use the {@link T_Ul_ResEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ res evaluacion.
	 *
	 * @return the primary key of this t_ ul_ res evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ res evaluacion.
	 *
	 * @param primaryKey the primary key of this t_ ul_ res evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ res evaluacion.
	 *
	 * @return the uuid of this t_ ul_ res evaluacion
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ res evaluacion.
	 *
	 * @param uuid the uuid of this t_ ul_ res evaluacion
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id respuestas of this t_ ul_ res evaluacion.
	 *
	 * @return the id respuestas of this t_ ul_ res evaluacion
	 */
	public long getIdRespuestas();

	/**
	 * Sets the id respuestas of this t_ ul_ res evaluacion.
	 *
	 * @param idRespuestas the id respuestas of this t_ ul_ res evaluacion
	 */
	public void setIdRespuestas(long idRespuestas);

	/**
	 * Returns the probl respuestas of this t_ ul_ res evaluacion.
	 *
	 * @return the probl respuestas of this t_ ul_ res evaluacion
	 */
	@AutoEscape
	public String getProblRespuestas();

	/**
	 * Sets the probl respuestas of this t_ ul_ res evaluacion.
	 *
	 * @param problRespuestas the probl respuestas of this t_ ul_ res evaluacion
	 */
	public void setProblRespuestas(String problRespuestas);

	/**
	 * Returns the opcion respuestas of this t_ ul_ res evaluacion.
	 *
	 * @return the opcion respuestas of this t_ ul_ res evaluacion
	 */
	@AutoEscape
	public String getOpcionRespuestas();

	/**
	 * Sets the opcion respuestas of this t_ ul_ res evaluacion.
	 *
	 * @param opcionRespuestas the opcion respuestas of this t_ ul_ res evaluacion
	 */
	public void setOpcionRespuestas(String opcionRespuestas);

	/**
	 * Returns the puntaje respuestas of this t_ ul_ res evaluacion.
	 *
	 * @return the puntaje respuestas of this t_ ul_ res evaluacion
	 */
	@AutoEscape
	public String getPuntajeRespuestas();

	/**
	 * Sets the puntaje respuestas of this t_ ul_ res evaluacion.
	 *
	 * @param puntajeRespuestas the puntaje respuestas of this t_ ul_ res evaluacion
	 */
	public void setPuntajeRespuestas(String puntajeRespuestas);

	/**
	 * Returns the t_ ul_ estudiante_id of this t_ ul_ res evaluacion.
	 *
	 * @return the t_ ul_ estudiante_id of this t_ ul_ res evaluacion
	 */
	public long getT_Ul_Estudiante_id();

	/**
	 * Sets the t_ ul_ estudiante_id of this t_ ul_ res evaluacion.
	 *
	 * @param T_Ul_Estudiante_id the t_ ul_ estudiante_id of this t_ ul_ res evaluacion
	 */
	public void setT_Ul_Estudiante_id(long T_Ul_Estudiante_id);

	/**
	 * Returns the t_ ul_ prg evaluacion_id of this t_ ul_ res evaluacion.
	 *
	 * @return the t_ ul_ prg evaluacion_id of this t_ ul_ res evaluacion
	 */
	public long getT_Ul_PrgEvaluacion_id();

	/**
	 * Sets the t_ ul_ prg evaluacion_id of this t_ ul_ res evaluacion.
	 *
	 * @param T_Ul_PrgEvaluacion_id the t_ ul_ prg evaluacion_id of this t_ ul_ res evaluacion
	 */
	public void setT_Ul_PrgEvaluacion_id(long T_Ul_PrgEvaluacion_id);

	/**
	 * Returns the t_ ul_ califi_id of this t_ ul_ res evaluacion.
	 *
	 * @return the t_ ul_ califi_id of this t_ ul_ res evaluacion
	 */
	public long getT_Ul_Califi_id();

	/**
	 * Sets the t_ ul_ califi_id of this t_ ul_ res evaluacion.
	 *
	 * @param T_Ul_Califi_id the t_ ul_ califi_id of this t_ ul_ res evaluacion
	 */
	public void setT_Ul_Califi_id(long T_Ul_Califi_id);

	/**
	 * Returns the group ID of this t_ ul_ res evaluacion.
	 *
	 * @return the group ID of this t_ ul_ res evaluacion
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ res evaluacion.
	 *
	 * @param groupId the group ID of this t_ ul_ res evaluacion
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ res evaluacion.
	 *
	 * @return the company ID of this t_ ul_ res evaluacion
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ res evaluacion.
	 *
	 * @param companyId the company ID of this t_ ul_ res evaluacion
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ res evaluacion.
	 *
	 * @return the user ID of this t_ ul_ res evaluacion
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ res evaluacion.
	 *
	 * @param userId the user ID of this t_ ul_ res evaluacion
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ res evaluacion.
	 *
	 * @return the user uuid of this t_ ul_ res evaluacion
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ res evaluacion.
	 *
	 * @param userUuid the user uuid of this t_ ul_ res evaluacion
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ res evaluacion.
	 *
	 * @return the user name of this t_ ul_ res evaluacion
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ res evaluacion.
	 *
	 * @param userName the user name of this t_ ul_ res evaluacion
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ res evaluacion.
	 *
	 * @return the create date of this t_ ul_ res evaluacion
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ res evaluacion.
	 *
	 * @param createDate the create date of this t_ ul_ res evaluacion
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ res evaluacion.
	 *
	 * @return the modified date of this t_ ul_ res evaluacion
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ res evaluacion.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ res evaluacion
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}