/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_MaterialEstud service. Represents a row in the &quot;AulaVirtual_T_Ul_MaterialEstud&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_MaterialEstudModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_MaterialEstudImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_MaterialEstud
 * @generated
 */
@ProviderType
public interface T_Ul_MaterialEstudModel
	extends BaseModel<T_Ul_MaterialEstud>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ material estud model instance should use the {@link T_Ul_MaterialEstud} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ material estud.
	 *
	 * @return the primary key of this t_ ul_ material estud
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ material estud.
	 *
	 * @param primaryKey the primary key of this t_ ul_ material estud
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ material estud.
	 *
	 * @return the uuid of this t_ ul_ material estud
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ material estud.
	 *
	 * @param uuid the uuid of this t_ ul_ material estud
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id material of this t_ ul_ material estud.
	 *
	 * @return the id material of this t_ ul_ material estud
	 */
	public long getIdMaterial();

	/**
	 * Sets the id material of this t_ ul_ material estud.
	 *
	 * @param idMaterial the id material of this t_ ul_ material estud
	 */
	public void setIdMaterial(long idMaterial);

	/**
	 * Returns the titulo material of this t_ ul_ material estud.
	 *
	 * @return the titulo material of this t_ ul_ material estud
	 */
	@AutoEscape
	public String getTituloMaterial();

	/**
	 * Sets the titulo material of this t_ ul_ material estud.
	 *
	 * @param tituloMaterial the titulo material of this t_ ul_ material estud
	 */
	public void setTituloMaterial(String tituloMaterial);

	/**
	 * Returns the f creacion material of this t_ ul_ material estud.
	 *
	 * @return the f creacion material of this t_ ul_ material estud
	 */
	public Date getFCreacionMaterial();

	/**
	 * Sets the f creacion material of this t_ ul_ material estud.
	 *
	 * @param fCreacionMaterial the f creacion material of this t_ ul_ material estud
	 */
	public void setFCreacionMaterial(Date fCreacionMaterial);

	/**
	 * Returns the url arch material of this t_ ul_ material estud.
	 *
	 * @return the url arch material of this t_ ul_ material estud
	 */
	@AutoEscape
	public String getUrlArchMaterial();

	/**
	 * Sets the url arch material of this t_ ul_ material estud.
	 *
	 * @param urlArchMaterial the url arch material of this t_ ul_ material estud
	 */
	public void setUrlArchMaterial(String urlArchMaterial);

	/**
	 * Returns the descrip material of this t_ ul_ material estud.
	 *
	 * @return the descrip material of this t_ ul_ material estud
	 */
	@AutoEscape
	public String getDescripMaterial();

	/**
	 * Sets the descrip material of this t_ ul_ material estud.
	 *
	 * @param descripMaterial the descrip material of this t_ ul_ material estud
	 */
	public void setDescripMaterial(String descripMaterial);

	/**
	 * Returns the t_ ul_p academico_id of this t_ ul_ material estud.
	 *
	 * @return the t_ ul_p academico_id of this t_ ul_ material estud
	 */
	public long getT_Ul_PAcademico_id();

	/**
	 * Sets the t_ ul_p academico_id of this t_ ul_ material estud.
	 *
	 * @param T_Ul_PAcademico_id the t_ ul_p academico_id of this t_ ul_ material estud
	 */
	public void setT_Ul_PAcademico_id(long T_Ul_PAcademico_id);

	/**
	 * Returns the group ID of this t_ ul_ material estud.
	 *
	 * @return the group ID of this t_ ul_ material estud
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ material estud.
	 *
	 * @param groupId the group ID of this t_ ul_ material estud
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ material estud.
	 *
	 * @return the company ID of this t_ ul_ material estud
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ material estud.
	 *
	 * @param companyId the company ID of this t_ ul_ material estud
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ material estud.
	 *
	 * @return the user ID of this t_ ul_ material estud
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ material estud.
	 *
	 * @param userId the user ID of this t_ ul_ material estud
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ material estud.
	 *
	 * @return the user uuid of this t_ ul_ material estud
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ material estud.
	 *
	 * @param userUuid the user uuid of this t_ ul_ material estud
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ material estud.
	 *
	 * @return the user name of this t_ ul_ material estud
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ material estud.
	 *
	 * @param userName the user name of this t_ ul_ material estud
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ material estud.
	 *
	 * @return the create date of this t_ ul_ material estud
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ material estud.
	 *
	 * @param createDate the create date of this t_ ul_ material estud
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ material estud.
	 *
	 * @return the modified date of this t_ ul_ material estud
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ material estud.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ material estud
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}