/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.aula.sb.service.persistence.T_Ul_AdminCursoPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_AdminCurso service. Represents a row in the &quot;AulaVirtual_T_Ul_AdminCurso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_AdminCursoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_AdminCursoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_AdminCurso
 * @generated
 */
@ProviderType
public interface T_Ul_AdminCursoModel
	extends BaseModel<T_Ul_AdminCurso>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ admin curso model instance should use the {@link T_Ul_AdminCurso} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ admin curso.
	 *
	 * @return the primary key of this t_ ul_ admin curso
	 */
	public T_Ul_AdminCursoPK getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ admin curso.
	 *
	 * @param primaryKey the primary key of this t_ ul_ admin curso
	 */
	public void setPrimaryKey(T_Ul_AdminCursoPK primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ admin curso.
	 *
	 * @return the uuid of this t_ ul_ admin curso
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ admin curso.
	 *
	 * @param uuid the uuid of this t_ ul_ admin curso
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the t_ ul_ admin_id of this t_ ul_ admin curso.
	 *
	 * @return the t_ ul_ admin_id of this t_ ul_ admin curso
	 */
	public long getT_Ul_Admin_id();

	/**
	 * Sets the t_ ul_ admin_id of this t_ ul_ admin curso.
	 *
	 * @param T_Ul_Admin_id the t_ ul_ admin_id of this t_ ul_ admin curso
	 */
	public void setT_Ul_Admin_id(long T_Ul_Admin_id);

	/**
	 * Returns the t_ ul_ curso_id of this t_ ul_ admin curso.
	 *
	 * @return the t_ ul_ curso_id of this t_ ul_ admin curso
	 */
	public long getT_Ul_Curso_id();

	/**
	 * Sets the t_ ul_ curso_id of this t_ ul_ admin curso.
	 *
	 * @param T_Ul_Curso_id the t_ ul_ curso_id of this t_ ul_ admin curso
	 */
	public void setT_Ul_Curso_id(long T_Ul_Curso_id);

	/**
	 * Returns the group ID of this t_ ul_ admin curso.
	 *
	 * @return the group ID of this t_ ul_ admin curso
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ admin curso.
	 *
	 * @param groupId the group ID of this t_ ul_ admin curso
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ admin curso.
	 *
	 * @return the company ID of this t_ ul_ admin curso
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ admin curso.
	 *
	 * @param companyId the company ID of this t_ ul_ admin curso
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ admin curso.
	 *
	 * @return the user ID of this t_ ul_ admin curso
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ admin curso.
	 *
	 * @param userId the user ID of this t_ ul_ admin curso
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ admin curso.
	 *
	 * @return the user uuid of this t_ ul_ admin curso
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ admin curso.
	 *
	 * @param userUuid the user uuid of this t_ ul_ admin curso
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ admin curso.
	 *
	 * @return the user name of this t_ ul_ admin curso
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ admin curso.
	 *
	 * @param userName the user name of this t_ ul_ admin curso
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ admin curso.
	 *
	 * @return the create date of this t_ ul_ admin curso
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ admin curso.
	 *
	 * @param createDate the create date of this t_ ul_ admin curso
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ admin curso.
	 *
	 * @return the modified date of this t_ ul_ admin curso
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ admin curso.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ admin curso
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}