/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_Estudiante service. Represents a row in the &quot;AulaVirtual_T_Ul_Estudiante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_EstudianteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_EstudianteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_Estudiante
 * @generated
 */
@ProviderType
public interface T_Ul_EstudianteModel
	extends BaseModel<T_Ul_Estudiante>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ estudiante model instance should use the {@link T_Ul_Estudiante} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ estudiante.
	 *
	 * @return the primary key of this t_ ul_ estudiante
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ estudiante.
	 *
	 * @param primaryKey the primary key of this t_ ul_ estudiante
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ estudiante.
	 *
	 * @return the uuid of this t_ ul_ estudiante
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ estudiante.
	 *
	 * @param uuid the uuid of this t_ ul_ estudiante
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id estudiante of this t_ ul_ estudiante.
	 *
	 * @return the id estudiante of this t_ ul_ estudiante
	 */
	public long getIdEstudiante();

	/**
	 * Sets the id estudiante of this t_ ul_ estudiante.
	 *
	 * @param idEstudiante the id estudiante of this t_ ul_ estudiante
	 */
	public void setIdEstudiante(long idEstudiante);

	/**
	 * Returns the nombre estudiante of this t_ ul_ estudiante.
	 *
	 * @return the nombre estudiante of this t_ ul_ estudiante
	 */
	@AutoEscape
	public String getNombreEstudiante();

	/**
	 * Sets the nombre estudiante of this t_ ul_ estudiante.
	 *
	 * @param nombreEstudiante the nombre estudiante of this t_ ul_ estudiante
	 */
	public void setNombreEstudiante(String nombreEstudiante);

	/**
	 * Returns the correo estudiante of this t_ ul_ estudiante.
	 *
	 * @return the correo estudiante of this t_ ul_ estudiante
	 */
	@AutoEscape
	public String getCorreoEstudiante();

	/**
	 * Sets the correo estudiante of this t_ ul_ estudiante.
	 *
	 * @param correoEstudiante the correo estudiante of this t_ ul_ estudiante
	 */
	public void setCorreoEstudiante(String correoEstudiante);

	/**
	 * Returns the profes estudiante of this t_ ul_ estudiante.
	 *
	 * @return the profes estudiante of this t_ ul_ estudiante
	 */
	@AutoEscape
	public String getProfesEstudiante();

	/**
	 * Sets the profes estudiante of this t_ ul_ estudiante.
	 *
	 * @param profesEstudiante the profes estudiante of this t_ ul_ estudiante
	 */
	public void setProfesEstudiante(String profesEstudiante);

	/**
	 * Returns the sede estudiante of this t_ ul_ estudiante.
	 *
	 * @return the sede estudiante of this t_ ul_ estudiante
	 */
	@AutoEscape
	public String getSedeEstudiante();

	/**
	 * Sets the sede estudiante of this t_ ul_ estudiante.
	 *
	 * @param sedeEstudiante the sede estudiante of this t_ ul_ estudiante
	 */
	public void setSedeEstudiante(String sedeEstudiante);

	/**
	 * Returns the group ID of this t_ ul_ estudiante.
	 *
	 * @return the group ID of this t_ ul_ estudiante
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ estudiante.
	 *
	 * @param groupId the group ID of this t_ ul_ estudiante
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ estudiante.
	 *
	 * @return the company ID of this t_ ul_ estudiante
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ estudiante.
	 *
	 * @param companyId the company ID of this t_ ul_ estudiante
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ estudiante.
	 *
	 * @return the user ID of this t_ ul_ estudiante
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ estudiante.
	 *
	 * @param userId the user ID of this t_ ul_ estudiante
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ estudiante.
	 *
	 * @return the user uuid of this t_ ul_ estudiante
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ estudiante.
	 *
	 * @param userUuid the user uuid of this t_ ul_ estudiante
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ estudiante.
	 *
	 * @return the user name of this t_ ul_ estudiante
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ estudiante.
	 *
	 * @param userName the user name of this t_ ul_ estudiante
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ estudiante.
	 *
	 * @return the create date of this t_ ul_ estudiante
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ estudiante.
	 *
	 * @param createDate the create date of this t_ ul_ estudiante
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ estudiante.
	 *
	 * @return the modified date of this t_ ul_ estudiante
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ estudiante.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ estudiante
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}