/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the T_Ul_PrgEvaluacion service. Represents a row in the &quot;AulaVirtual_T_Ul_PrgEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aula.sb.model.impl.T_Ul_PrgEvaluacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aula.sb.model.impl.T_Ul_PrgEvaluacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_PrgEvaluacion
 * @generated
 */
@ProviderType
public interface T_Ul_PrgEvaluacionModel
	extends BaseModel<T_Ul_PrgEvaluacion>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t_ ul_ prg evaluacion model instance should use the {@link T_Ul_PrgEvaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this t_ ul_ prg evaluacion.
	 *
	 * @return the primary key of this t_ ul_ prg evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t_ ul_ prg evaluacion.
	 *
	 * @param primaryKey the primary key of this t_ ul_ prg evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this t_ ul_ prg evaluacion.
	 *
	 * @return the uuid of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this t_ ul_ prg evaluacion.
	 *
	 * @param uuid the uuid of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the id preguntas of this t_ ul_ prg evaluacion
	 */
	public long getIdPreguntas();

	/**
	 * Sets the id preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param idPreguntas the id preguntas of this t_ ul_ prg evaluacion
	 */
	public void setIdPreguntas(long idPreguntas);

	/**
	 * Returns the probl preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the probl preguntas of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	public String getProblPreguntas();

	/**
	 * Sets the probl preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param problPreguntas the probl preguntas of this t_ ul_ prg evaluacion
	 */
	public void setProblPreguntas(String problPreguntas);

	/**
	 * Returns the opc preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the opc preguntas of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	public String getOpcPreguntas();

	/**
	 * Sets the opc preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param opcPreguntas the opc preguntas of this t_ ul_ prg evaluacion
	 */
	public void setOpcPreguntas(String opcPreguntas);

	/**
	 * Returns the puntaje preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the puntaje preguntas of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	public String getPuntajePreguntas();

	/**
	 * Sets the puntaje preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param puntajePreguntas the puntaje preguntas of this t_ ul_ prg evaluacion
	 */
	public void setPuntajePreguntas(String puntajePreguntas);

	/**
	 * Returns the intento preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the intento preguntas of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	public String getIntentoPreguntas();

	/**
	 * Sets the intento preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param intentoPreguntas the intento preguntas of this t_ ul_ prg evaluacion
	 */
	public void setIntentoPreguntas(String intentoPreguntas);

	/**
	 * Returns the limite t preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @return the limite t preguntas of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	public String getLimiteTPreguntas();

	/**
	 * Sets the limite t preguntas of this t_ ul_ prg evaluacion.
	 *
	 * @param limiteTPreguntas the limite t preguntas of this t_ ul_ prg evaluacion
	 */
	public void setLimiteTPreguntas(String limiteTPreguntas);

	/**
	 * Returns the t_ ul_ actividad_id of this t_ ul_ prg evaluacion.
	 *
	 * @return the t_ ul_ actividad_id of this t_ ul_ prg evaluacion
	 */
	public long getT_Ul_Actividad_id();

	/**
	 * Sets the t_ ul_ actividad_id of this t_ ul_ prg evaluacion.
	 *
	 * @param T_Ul_Actividad_id the t_ ul_ actividad_id of this t_ ul_ prg evaluacion
	 */
	public void setT_Ul_Actividad_id(long T_Ul_Actividad_id);

	/**
	 * Returns the group ID of this t_ ul_ prg evaluacion.
	 *
	 * @return the group ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t_ ul_ prg evaluacion.
	 *
	 * @param groupId the group ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t_ ul_ prg evaluacion.
	 *
	 * @return the company ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t_ ul_ prg evaluacion.
	 *
	 * @param companyId the company ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t_ ul_ prg evaluacion.
	 *
	 * @return the user ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t_ ul_ prg evaluacion.
	 *
	 * @param userId the user ID of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t_ ul_ prg evaluacion.
	 *
	 * @return the user uuid of this t_ ul_ prg evaluacion
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this t_ ul_ prg evaluacion.
	 *
	 * @param userUuid the user uuid of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t_ ul_ prg evaluacion.
	 *
	 * @return the user name of this t_ ul_ prg evaluacion
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t_ ul_ prg evaluacion.
	 *
	 * @param userName the user name of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t_ ul_ prg evaluacion.
	 *
	 * @return the create date of this t_ ul_ prg evaluacion
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t_ ul_ prg evaluacion.
	 *
	 * @param createDate the create date of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t_ ul_ prg evaluacion.
	 *
	 * @return the modified date of this t_ ul_ prg evaluacion
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t_ ul_ prg evaluacion.
	 *
	 * @param modifiedDate the modified date of this t_ ul_ prg evaluacion
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}