/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model.impl;

import com.aula.sb.model.T_Ul_Curso;
import com.aula.sb.model.T_Ul_CursoModel;
import com.aula.sb.model.T_Ul_CursoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the T_Ul_Curso service. Represents a row in the &quot;AulaVirtual_T_Ul_Curso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>T_Ul_CursoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T_Ul_CursoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_CursoImpl
 * @generated
 */
@JSON(strict = true)
public class T_Ul_CursoModelImpl
	extends BaseModelImpl<T_Ul_Curso> implements T_Ul_CursoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_ ul_ curso model instance should use the <code>T_Ul_Curso</code> interface instead.
	 */
	public static final String TABLE_NAME = "AulaVirtual_T_Ul_Curso";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idCurso", Types.BIGINT},
		{"nombreCurso", Types.VARCHAR}, {"fInicioCurso", Types.TIMESTAMP},
		{"fFinCurso", Types.TIMESTAMP}, {"colorCurso", Types.VARCHAR},
		{"T_Ul_Califi_id", Types.BIGINT}, {"T_Ul_Profesor_id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idCurso", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nombreCurso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fInicioCurso", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fFinCurso", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("colorCurso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("T_Ul_Califi_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("T_Ul_Profesor_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AulaVirtual_T_Ul_Curso (uuid_ VARCHAR(75) null,idCurso LONG not null primary key,nombreCurso VARCHAR(75) null,fInicioCurso DATE null,fFinCurso DATE null,colorCurso VARCHAR(75) null,T_Ul_Califi_id LONG,T_Ul_Profesor_id LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AulaVirtual_T_Ul_Curso";

	public static final String ORDER_BY_JPQL =
		" ORDER BY t_Ul_Curso.idCurso ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AulaVirtual_T_Ul_Curso.idCurso ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMBRECURSO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDCURSO_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static T_Ul_Curso toModel(T_Ul_CursoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		T_Ul_Curso model = new T_Ul_CursoImpl();

		model.setUuid(soapModel.getUuid());
		model.setIdCurso(soapModel.getIdCurso());
		model.setNombreCurso(soapModel.getNombreCurso());
		model.setFInicioCurso(soapModel.getFInicioCurso());
		model.setFFinCurso(soapModel.getFFinCurso());
		model.setColorCurso(soapModel.getColorCurso());
		model.setT_Ul_Califi_id(soapModel.getT_Ul_Califi_id());
		model.setT_Ul_Profesor_id(soapModel.getT_Ul_Profesor_id());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<T_Ul_Curso> toModels(T_Ul_CursoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<T_Ul_Curso> models = new ArrayList<T_Ul_Curso>(soapModels.length);

		for (T_Ul_CursoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public T_Ul_CursoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idCurso;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdCurso(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idCurso;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return T_Ul_Curso.class;
	}

	@Override
	public String getModelClassName() {
		return T_Ul_Curso.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<T_Ul_Curso, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<T_Ul_Curso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_Curso, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((T_Ul_Curso)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<T_Ul_Curso, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<T_Ul_Curso, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(T_Ul_Curso)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<T_Ul_Curso, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<T_Ul_Curso, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<T_Ul_Curso, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<T_Ul_Curso, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<T_Ul_Curso, Object>>();

		attributeGetterFunctions.put("uuid", T_Ul_Curso::getUuid);
		attributeGetterFunctions.put("idCurso", T_Ul_Curso::getIdCurso);
		attributeGetterFunctions.put("nombreCurso", T_Ul_Curso::getNombreCurso);
		attributeGetterFunctions.put(
			"fInicioCurso", T_Ul_Curso::getFInicioCurso);
		attributeGetterFunctions.put("fFinCurso", T_Ul_Curso::getFFinCurso);
		attributeGetterFunctions.put("colorCurso", T_Ul_Curso::getColorCurso);
		attributeGetterFunctions.put(
			"T_Ul_Califi_id", T_Ul_Curso::getT_Ul_Califi_id);
		attributeGetterFunctions.put(
			"T_Ul_Profesor_id", T_Ul_Curso::getT_Ul_Profesor_id);
		attributeGetterFunctions.put("groupId", T_Ul_Curso::getGroupId);
		attributeGetterFunctions.put("companyId", T_Ul_Curso::getCompanyId);
		attributeGetterFunctions.put("userId", T_Ul_Curso::getUserId);
		attributeGetterFunctions.put("userName", T_Ul_Curso::getUserName);
		attributeGetterFunctions.put("createDate", T_Ul_Curso::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", T_Ul_Curso::getModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<T_Ul_Curso, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<T_Ul_Curso, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<T_Ul_Curso, ?>>();

		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<T_Ul_Curso, String>)T_Ul_Curso::setUuid);
		attributeSetterBiConsumers.put(
			"idCurso", (BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setIdCurso);
		attributeSetterBiConsumers.put(
			"nombreCurso",
			(BiConsumer<T_Ul_Curso, String>)T_Ul_Curso::setNombreCurso);
		attributeSetterBiConsumers.put(
			"fInicioCurso",
			(BiConsumer<T_Ul_Curso, Date>)T_Ul_Curso::setFInicioCurso);
		attributeSetterBiConsumers.put(
			"fFinCurso",
			(BiConsumer<T_Ul_Curso, Date>)T_Ul_Curso::setFFinCurso);
		attributeSetterBiConsumers.put(
			"colorCurso",
			(BiConsumer<T_Ul_Curso, String>)T_Ul_Curso::setColorCurso);
		attributeSetterBiConsumers.put(
			"T_Ul_Califi_id",
			(BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setT_Ul_Califi_id);
		attributeSetterBiConsumers.put(
			"T_Ul_Profesor_id",
			(BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setT_Ul_Profesor_id);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<T_Ul_Curso, Long>)T_Ul_Curso::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<T_Ul_Curso, String>)T_Ul_Curso::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<T_Ul_Curso, Date>)T_Ul_Curso::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<T_Ul_Curso, Date>)T_Ul_Curso::setModifiedDate);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdCurso() {
		return _idCurso;
	}

	@Override
	public void setIdCurso(long idCurso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idCurso = idCurso;
	}

	@JSON
	@Override
	public String getNombreCurso() {
		if (_nombreCurso == null) {
			return "";
		}
		else {
			return _nombreCurso;
		}
	}

	@Override
	public void setNombreCurso(String nombreCurso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nombreCurso = nombreCurso;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNombreCurso() {
		return getColumnOriginalValue("nombreCurso");
	}

	@JSON
	@Override
	public Date getFInicioCurso() {
		return _fInicioCurso;
	}

	@Override
	public void setFInicioCurso(Date fInicioCurso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fInicioCurso = fInicioCurso;
	}

	@JSON
	@Override
	public Date getFFinCurso() {
		return _fFinCurso;
	}

	@Override
	public void setFFinCurso(Date fFinCurso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fFinCurso = fFinCurso;
	}

	@JSON
	@Override
	public String getColorCurso() {
		if (_colorCurso == null) {
			return "";
		}
		else {
			return _colorCurso;
		}
	}

	@Override
	public void setColorCurso(String colorCurso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_colorCurso = colorCurso;
	}

	@JSON
	@Override
	public long getT_Ul_Califi_id() {
		return _T_Ul_Califi_id;
	}

	@Override
	public void setT_Ul_Califi_id(long T_Ul_Califi_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_Califi_id = T_Ul_Califi_id;
	}

	@JSON
	@Override
	public long getT_Ul_Profesor_id() {
		return _T_Ul_Profesor_id;
	}

	@Override
	public void setT_Ul_Profesor_id(long T_Ul_Profesor_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_Profesor_id = T_Ul_Profesor_id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(T_Ul_Curso.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), T_Ul_Curso.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public T_Ul_Curso toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, T_Ul_Curso>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		T_Ul_CursoImpl t_Ul_CursoImpl = new T_Ul_CursoImpl();

		t_Ul_CursoImpl.setUuid(getUuid());
		t_Ul_CursoImpl.setIdCurso(getIdCurso());
		t_Ul_CursoImpl.setNombreCurso(getNombreCurso());
		t_Ul_CursoImpl.setFInicioCurso(getFInicioCurso());
		t_Ul_CursoImpl.setFFinCurso(getFFinCurso());
		t_Ul_CursoImpl.setColorCurso(getColorCurso());
		t_Ul_CursoImpl.setT_Ul_Califi_id(getT_Ul_Califi_id());
		t_Ul_CursoImpl.setT_Ul_Profesor_id(getT_Ul_Profesor_id());
		t_Ul_CursoImpl.setGroupId(getGroupId());
		t_Ul_CursoImpl.setCompanyId(getCompanyId());
		t_Ul_CursoImpl.setUserId(getUserId());
		t_Ul_CursoImpl.setUserName(getUserName());
		t_Ul_CursoImpl.setCreateDate(getCreateDate());
		t_Ul_CursoImpl.setModifiedDate(getModifiedDate());

		t_Ul_CursoImpl.resetOriginalValues();

		return t_Ul_CursoImpl;
	}

	@Override
	public int compareTo(T_Ul_Curso t_Ul_Curso) {
		int value = 0;

		if (getIdCurso() < t_Ul_Curso.getIdCurso()) {
			value = -1;
		}
		else if (getIdCurso() > t_Ul_Curso.getIdCurso()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof T_Ul_Curso)) {
			return false;
		}

		T_Ul_Curso t_Ul_Curso = (T_Ul_Curso)object;

		long primaryKey = t_Ul_Curso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<T_Ul_Curso> toCacheModel() {
		T_Ul_CursoCacheModel t_Ul_CursoCacheModel = new T_Ul_CursoCacheModel();

		t_Ul_CursoCacheModel.uuid = getUuid();

		String uuid = t_Ul_CursoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			t_Ul_CursoCacheModel.uuid = null;
		}

		t_Ul_CursoCacheModel.idCurso = getIdCurso();

		t_Ul_CursoCacheModel.nombreCurso = getNombreCurso();

		String nombreCurso = t_Ul_CursoCacheModel.nombreCurso;

		if ((nombreCurso != null) && (nombreCurso.length() == 0)) {
			t_Ul_CursoCacheModel.nombreCurso = null;
		}

		Date fInicioCurso = getFInicioCurso();

		if (fInicioCurso != null) {
			t_Ul_CursoCacheModel.fInicioCurso = fInicioCurso.getTime();
		}
		else {
			t_Ul_CursoCacheModel.fInicioCurso = Long.MIN_VALUE;
		}

		Date fFinCurso = getFFinCurso();

		if (fFinCurso != null) {
			t_Ul_CursoCacheModel.fFinCurso = fFinCurso.getTime();
		}
		else {
			t_Ul_CursoCacheModel.fFinCurso = Long.MIN_VALUE;
		}

		t_Ul_CursoCacheModel.colorCurso = getColorCurso();

		String colorCurso = t_Ul_CursoCacheModel.colorCurso;

		if ((colorCurso != null) && (colorCurso.length() == 0)) {
			t_Ul_CursoCacheModel.colorCurso = null;
		}

		t_Ul_CursoCacheModel.T_Ul_Califi_id = getT_Ul_Califi_id();

		t_Ul_CursoCacheModel.T_Ul_Profesor_id = getT_Ul_Profesor_id();

		t_Ul_CursoCacheModel.groupId = getGroupId();

		t_Ul_CursoCacheModel.companyId = getCompanyId();

		t_Ul_CursoCacheModel.userId = getUserId();

		t_Ul_CursoCacheModel.userName = getUserName();

		String userName = t_Ul_CursoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			t_Ul_CursoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			t_Ul_CursoCacheModel.createDate = createDate.getTime();
		}
		else {
			t_Ul_CursoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			t_Ul_CursoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			t_Ul_CursoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return t_Ul_CursoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<T_Ul_Curso, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<T_Ul_Curso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_Curso, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((T_Ul_Curso)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<T_Ul_Curso, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<T_Ul_Curso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_Curso, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((T_Ul_Curso)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, T_Ul_Curso>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					T_Ul_Curso.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idCurso;
	private String _nombreCurso;
	private Date _fInicioCurso;
	private Date _fFinCurso;
	private String _colorCurso;
	private long _T_Ul_Califi_id;
	private long _T_Ul_Profesor_id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<T_Ul_Curso, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((T_Ul_Curso)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idCurso", _idCurso);
		_columnOriginalValues.put("nombreCurso", _nombreCurso);
		_columnOriginalValues.put("fInicioCurso", _fInicioCurso);
		_columnOriginalValues.put("fFinCurso", _fFinCurso);
		_columnOriginalValues.put("colorCurso", _colorCurso);
		_columnOriginalValues.put("T_Ul_Califi_id", _T_Ul_Califi_id);
		_columnOriginalValues.put("T_Ul_Profesor_id", _T_Ul_Profesor_id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idCurso", 2L);

		columnBitmasks.put("nombreCurso", 4L);

		columnBitmasks.put("fInicioCurso", 8L);

		columnBitmasks.put("fFinCurso", 16L);

		columnBitmasks.put("colorCurso", 32L);

		columnBitmasks.put("T_Ul_Califi_id", 64L);

		columnBitmasks.put("T_Ul_Profesor_id", 128L);

		columnBitmasks.put("groupId", 256L);

		columnBitmasks.put("companyId", 512L);

		columnBitmasks.put("userId", 1024L);

		columnBitmasks.put("userName", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private T_Ul_Curso _escapedModel;

}