/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model.impl;

import com.aula.sb.model.T_Ul_ResEvaluacion;
import com.aula.sb.model.T_Ul_ResEvaluacionModel;
import com.aula.sb.model.T_Ul_ResEvaluacionSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the T_Ul_ResEvaluacion service. Represents a row in the &quot;AulaVirtual_T_Ul_ResEvaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>T_Ul_ResEvaluacionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T_Ul_ResEvaluacionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_ResEvaluacionImpl
 * @generated
 */
@JSON(strict = true)
public class T_Ul_ResEvaluacionModelImpl
	extends BaseModelImpl<T_Ul_ResEvaluacion>
	implements T_Ul_ResEvaluacionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_ ul_ res evaluacion model instance should use the <code>T_Ul_ResEvaluacion</code> interface instead.
	 */
	public static final String TABLE_NAME = "AulaVirtual_T_Ul_ResEvaluacion";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idRespuestas", Types.BIGINT},
		{"problRespuestas", Types.VARCHAR}, {"opcionRespuestas", Types.VARCHAR},
		{"puntajeRespuestas", Types.VARCHAR},
		{"T_Ul_Estudiante_id", Types.BIGINT},
		{"T_Ul_PrgEvaluacion_id", Types.BIGINT},
		{"T_Ul_Califi_id", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idRespuestas", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("problRespuestas", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("opcionRespuestas", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("puntajeRespuestas", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("T_Ul_Estudiante_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("T_Ul_PrgEvaluacion_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("T_Ul_Califi_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AulaVirtual_T_Ul_ResEvaluacion (uuid_ VARCHAR(75) null,idRespuestas LONG not null primary key,problRespuestas VARCHAR(75) null,opcionRespuestas VARCHAR(75) null,puntajeRespuestas VARCHAR(75) null,T_Ul_Estudiante_id LONG,T_Ul_PrgEvaluacion_id LONG,T_Ul_Califi_id LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AulaVirtual_T_Ul_ResEvaluacion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY t_Ul_ResEvaluacion.idRespuestas ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AulaVirtual_T_Ul_ResEvaluacion.idRespuestas ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROBLRESPUESTAS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDRESPUESTAS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static T_Ul_ResEvaluacion toModel(T_Ul_ResEvaluacionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		T_Ul_ResEvaluacion model = new T_Ul_ResEvaluacionImpl();

		model.setUuid(soapModel.getUuid());
		model.setIdRespuestas(soapModel.getIdRespuestas());
		model.setProblRespuestas(soapModel.getProblRespuestas());
		model.setOpcionRespuestas(soapModel.getOpcionRespuestas());
		model.setPuntajeRespuestas(soapModel.getPuntajeRespuestas());
		model.setT_Ul_Estudiante_id(soapModel.getT_Ul_Estudiante_id());
		model.setT_Ul_PrgEvaluacion_id(soapModel.getT_Ul_PrgEvaluacion_id());
		model.setT_Ul_Califi_id(soapModel.getT_Ul_Califi_id());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<T_Ul_ResEvaluacion> toModels(
		T_Ul_ResEvaluacionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<T_Ul_ResEvaluacion> models = new ArrayList<T_Ul_ResEvaluacion>(
			soapModels.length);

		for (T_Ul_ResEvaluacionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public T_Ul_ResEvaluacionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idRespuestas;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdRespuestas(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idRespuestas;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return T_Ul_ResEvaluacion.class;
	}

	@Override
	public String getModelClassName() {
		return T_Ul_ResEvaluacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<T_Ul_ResEvaluacion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<T_Ul_ResEvaluacion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_ResEvaluacion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((T_Ul_ResEvaluacion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<T_Ul_ResEvaluacion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<T_Ul_ResEvaluacion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(T_Ul_ResEvaluacion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<T_Ul_ResEvaluacion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<T_Ul_ResEvaluacion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<T_Ul_ResEvaluacion, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<T_Ul_ResEvaluacion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<T_Ul_ResEvaluacion, Object>>();

		attributeGetterFunctions.put("uuid", T_Ul_ResEvaluacion::getUuid);
		attributeGetterFunctions.put(
			"idRespuestas", T_Ul_ResEvaluacion::getIdRespuestas);
		attributeGetterFunctions.put(
			"problRespuestas", T_Ul_ResEvaluacion::getProblRespuestas);
		attributeGetterFunctions.put(
			"opcionRespuestas", T_Ul_ResEvaluacion::getOpcionRespuestas);
		attributeGetterFunctions.put(
			"puntajeRespuestas", T_Ul_ResEvaluacion::getPuntajeRespuestas);
		attributeGetterFunctions.put(
			"T_Ul_Estudiante_id", T_Ul_ResEvaluacion::getT_Ul_Estudiante_id);
		attributeGetterFunctions.put(
			"T_Ul_PrgEvaluacion_id",
			T_Ul_ResEvaluacion::getT_Ul_PrgEvaluacion_id);
		attributeGetterFunctions.put(
			"T_Ul_Califi_id", T_Ul_ResEvaluacion::getT_Ul_Califi_id);
		attributeGetterFunctions.put("groupId", T_Ul_ResEvaluacion::getGroupId);
		attributeGetterFunctions.put(
			"companyId", T_Ul_ResEvaluacion::getCompanyId);
		attributeGetterFunctions.put("userId", T_Ul_ResEvaluacion::getUserId);
		attributeGetterFunctions.put(
			"userName", T_Ul_ResEvaluacion::getUserName);
		attributeGetterFunctions.put(
			"createDate", T_Ul_ResEvaluacion::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", T_Ul_ResEvaluacion::getModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<T_Ul_ResEvaluacion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<T_Ul_ResEvaluacion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<T_Ul_ResEvaluacion, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<T_Ul_ResEvaluacion, String>)
				T_Ul_ResEvaluacion::setUuid);
		attributeSetterBiConsumers.put(
			"idRespuestas",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setIdRespuestas);
		attributeSetterBiConsumers.put(
			"problRespuestas",
			(BiConsumer<T_Ul_ResEvaluacion, String>)
				T_Ul_ResEvaluacion::setProblRespuestas);
		attributeSetterBiConsumers.put(
			"opcionRespuestas",
			(BiConsumer<T_Ul_ResEvaluacion, String>)
				T_Ul_ResEvaluacion::setOpcionRespuestas);
		attributeSetterBiConsumers.put(
			"puntajeRespuestas",
			(BiConsumer<T_Ul_ResEvaluacion, String>)
				T_Ul_ResEvaluacion::setPuntajeRespuestas);
		attributeSetterBiConsumers.put(
			"T_Ul_Estudiante_id",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setT_Ul_Estudiante_id);
		attributeSetterBiConsumers.put(
			"T_Ul_PrgEvaluacion_id",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setT_Ul_PrgEvaluacion_id);
		attributeSetterBiConsumers.put(
			"T_Ul_Califi_id",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setT_Ul_Califi_id);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<T_Ul_ResEvaluacion, Long>)
				T_Ul_ResEvaluacion::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<T_Ul_ResEvaluacion, String>)
				T_Ul_ResEvaluacion::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<T_Ul_ResEvaluacion, Date>)
				T_Ul_ResEvaluacion::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<T_Ul_ResEvaluacion, Date>)
				T_Ul_ResEvaluacion::setModifiedDate);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdRespuestas() {
		return _idRespuestas;
	}

	@Override
	public void setIdRespuestas(long idRespuestas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idRespuestas = idRespuestas;
	}

	@JSON
	@Override
	public String getProblRespuestas() {
		if (_problRespuestas == null) {
			return "";
		}
		else {
			return _problRespuestas;
		}
	}

	@Override
	public void setProblRespuestas(String problRespuestas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_problRespuestas = problRespuestas;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalProblRespuestas() {
		return getColumnOriginalValue("problRespuestas");
	}

	@JSON
	@Override
	public String getOpcionRespuestas() {
		if (_opcionRespuestas == null) {
			return "";
		}
		else {
			return _opcionRespuestas;
		}
	}

	@Override
	public void setOpcionRespuestas(String opcionRespuestas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_opcionRespuestas = opcionRespuestas;
	}

	@JSON
	@Override
	public String getPuntajeRespuestas() {
		if (_puntajeRespuestas == null) {
			return "";
		}
		else {
			return _puntajeRespuestas;
		}
	}

	@Override
	public void setPuntajeRespuestas(String puntajeRespuestas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_puntajeRespuestas = puntajeRespuestas;
	}

	@JSON
	@Override
	public long getT_Ul_Estudiante_id() {
		return _T_Ul_Estudiante_id;
	}

	@Override
	public void setT_Ul_Estudiante_id(long T_Ul_Estudiante_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_Estudiante_id = T_Ul_Estudiante_id;
	}

	@JSON
	@Override
	public long getT_Ul_PrgEvaluacion_id() {
		return _T_Ul_PrgEvaluacion_id;
	}

	@Override
	public void setT_Ul_PrgEvaluacion_id(long T_Ul_PrgEvaluacion_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_PrgEvaluacion_id = T_Ul_PrgEvaluacion_id;
	}

	@JSON
	@Override
	public long getT_Ul_Califi_id() {
		return _T_Ul_Califi_id;
	}

	@Override
	public void setT_Ul_Califi_id(long T_Ul_Califi_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_Califi_id = T_Ul_Califi_id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(T_Ul_ResEvaluacion.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), T_Ul_ResEvaluacion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public T_Ul_ResEvaluacion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, T_Ul_ResEvaluacion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		T_Ul_ResEvaluacionImpl t_Ul_ResEvaluacionImpl =
			new T_Ul_ResEvaluacionImpl();

		t_Ul_ResEvaluacionImpl.setUuid(getUuid());
		t_Ul_ResEvaluacionImpl.setIdRespuestas(getIdRespuestas());
		t_Ul_ResEvaluacionImpl.setProblRespuestas(getProblRespuestas());
		t_Ul_ResEvaluacionImpl.setOpcionRespuestas(getOpcionRespuestas());
		t_Ul_ResEvaluacionImpl.setPuntajeRespuestas(getPuntajeRespuestas());
		t_Ul_ResEvaluacionImpl.setT_Ul_Estudiante_id(getT_Ul_Estudiante_id());
		t_Ul_ResEvaluacionImpl.setT_Ul_PrgEvaluacion_id(
			getT_Ul_PrgEvaluacion_id());
		t_Ul_ResEvaluacionImpl.setT_Ul_Califi_id(getT_Ul_Califi_id());
		t_Ul_ResEvaluacionImpl.setGroupId(getGroupId());
		t_Ul_ResEvaluacionImpl.setCompanyId(getCompanyId());
		t_Ul_ResEvaluacionImpl.setUserId(getUserId());
		t_Ul_ResEvaluacionImpl.setUserName(getUserName());
		t_Ul_ResEvaluacionImpl.setCreateDate(getCreateDate());
		t_Ul_ResEvaluacionImpl.setModifiedDate(getModifiedDate());

		t_Ul_ResEvaluacionImpl.resetOriginalValues();

		return t_Ul_ResEvaluacionImpl;
	}

	@Override
	public int compareTo(T_Ul_ResEvaluacion t_Ul_ResEvaluacion) {
		int value = 0;

		if (getIdRespuestas() < t_Ul_ResEvaluacion.getIdRespuestas()) {
			value = -1;
		}
		else if (getIdRespuestas() > t_Ul_ResEvaluacion.getIdRespuestas()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof T_Ul_ResEvaluacion)) {
			return false;
		}

		T_Ul_ResEvaluacion t_Ul_ResEvaluacion = (T_Ul_ResEvaluacion)object;

		long primaryKey = t_Ul_ResEvaluacion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<T_Ul_ResEvaluacion> toCacheModel() {
		T_Ul_ResEvaluacionCacheModel t_Ul_ResEvaluacionCacheModel =
			new T_Ul_ResEvaluacionCacheModel();

		t_Ul_ResEvaluacionCacheModel.uuid = getUuid();

		String uuid = t_Ul_ResEvaluacionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			t_Ul_ResEvaluacionCacheModel.uuid = null;
		}

		t_Ul_ResEvaluacionCacheModel.idRespuestas = getIdRespuestas();

		t_Ul_ResEvaluacionCacheModel.problRespuestas = getProblRespuestas();

		String problRespuestas = t_Ul_ResEvaluacionCacheModel.problRespuestas;

		if ((problRespuestas != null) && (problRespuestas.length() == 0)) {
			t_Ul_ResEvaluacionCacheModel.problRespuestas = null;
		}

		t_Ul_ResEvaluacionCacheModel.opcionRespuestas = getOpcionRespuestas();

		String opcionRespuestas = t_Ul_ResEvaluacionCacheModel.opcionRespuestas;

		if ((opcionRespuestas != null) && (opcionRespuestas.length() == 0)) {
			t_Ul_ResEvaluacionCacheModel.opcionRespuestas = null;
		}

		t_Ul_ResEvaluacionCacheModel.puntajeRespuestas = getPuntajeRespuestas();

		String puntajeRespuestas =
			t_Ul_ResEvaluacionCacheModel.puntajeRespuestas;

		if ((puntajeRespuestas != null) && (puntajeRespuestas.length() == 0)) {
			t_Ul_ResEvaluacionCacheModel.puntajeRespuestas = null;
		}

		t_Ul_ResEvaluacionCacheModel.T_Ul_Estudiante_id =
			getT_Ul_Estudiante_id();

		t_Ul_ResEvaluacionCacheModel.T_Ul_PrgEvaluacion_id =
			getT_Ul_PrgEvaluacion_id();

		t_Ul_ResEvaluacionCacheModel.T_Ul_Califi_id = getT_Ul_Califi_id();

		t_Ul_ResEvaluacionCacheModel.groupId = getGroupId();

		t_Ul_ResEvaluacionCacheModel.companyId = getCompanyId();

		t_Ul_ResEvaluacionCacheModel.userId = getUserId();

		t_Ul_ResEvaluacionCacheModel.userName = getUserName();

		String userName = t_Ul_ResEvaluacionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			t_Ul_ResEvaluacionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			t_Ul_ResEvaluacionCacheModel.createDate = createDate.getTime();
		}
		else {
			t_Ul_ResEvaluacionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			t_Ul_ResEvaluacionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			t_Ul_ResEvaluacionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return t_Ul_ResEvaluacionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<T_Ul_ResEvaluacion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<T_Ul_ResEvaluacion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_ResEvaluacion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(T_Ul_ResEvaluacion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<T_Ul_ResEvaluacion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<T_Ul_ResEvaluacion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_ResEvaluacion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((T_Ul_ResEvaluacion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, T_Ul_ResEvaluacion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					T_Ul_ResEvaluacion.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idRespuestas;
	private String _problRespuestas;
	private String _opcionRespuestas;
	private String _puntajeRespuestas;
	private long _T_Ul_Estudiante_id;
	private long _T_Ul_PrgEvaluacion_id;
	private long _T_Ul_Califi_id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<T_Ul_ResEvaluacion, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((T_Ul_ResEvaluacion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idRespuestas", _idRespuestas);
		_columnOriginalValues.put("problRespuestas", _problRespuestas);
		_columnOriginalValues.put("opcionRespuestas", _opcionRespuestas);
		_columnOriginalValues.put("puntajeRespuestas", _puntajeRespuestas);
		_columnOriginalValues.put("T_Ul_Estudiante_id", _T_Ul_Estudiante_id);
		_columnOriginalValues.put(
			"T_Ul_PrgEvaluacion_id", _T_Ul_PrgEvaluacion_id);
		_columnOriginalValues.put("T_Ul_Califi_id", _T_Ul_Califi_id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idRespuestas", 2L);

		columnBitmasks.put("problRespuestas", 4L);

		columnBitmasks.put("opcionRespuestas", 8L);

		columnBitmasks.put("puntajeRespuestas", 16L);

		columnBitmasks.put("T_Ul_Estudiante_id", 32L);

		columnBitmasks.put("T_Ul_PrgEvaluacion_id", 64L);

		columnBitmasks.put("T_Ul_Califi_id", 128L);

		columnBitmasks.put("groupId", 256L);

		columnBitmasks.put("companyId", 512L);

		columnBitmasks.put("userId", 1024L);

		columnBitmasks.put("userName", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private T_Ul_ResEvaluacion _escapedModel;

}