/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model.impl;

import com.aula.sb.model.T_Ul_PAcademico;
import com.aula.sb.service.T_Ul_PAcademicoLocalServiceUtil;

/**
 * The extended model base implementation for the T_Ul_PAcademico service. Represents a row in the &quot;AulaVirtual_T_Ul_PAcademico&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T_Ul_PAcademicoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_PAcademicoImpl
 * @see T_Ul_PAcademico
 * @generated
 */
public abstract class T_Ul_PAcademicoBaseImpl
	extends T_Ul_PAcademicoModelImpl implements T_Ul_PAcademico {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_ ul_p academico model instance should use the <code>T_Ul_PAcademico</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			T_Ul_PAcademicoLocalServiceUtil.addT_Ul_PAcademico(this);
		}
		else {
			T_Ul_PAcademicoLocalServiceUtil.updateT_Ul_PAcademico(this);
		}
	}

}