/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model.impl;

import com.aula.sb.model.T_Ul_MaterialEstud;
import com.aula.sb.model.T_Ul_MaterialEstudModel;
import com.aula.sb.model.T_Ul_MaterialEstudSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the T_Ul_MaterialEstud service. Represents a row in the &quot;AulaVirtual_T_Ul_MaterialEstud&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>T_Ul_MaterialEstudModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T_Ul_MaterialEstudImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_MaterialEstudImpl
 * @generated
 */
@JSON(strict = true)
public class T_Ul_MaterialEstudModelImpl
	extends BaseModelImpl<T_Ul_MaterialEstud>
	implements T_Ul_MaterialEstudModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_ ul_ material estud model instance should use the <code>T_Ul_MaterialEstud</code> interface instead.
	 */
	public static final String TABLE_NAME = "AulaVirtual_T_Ul_MaterialEstud";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"idMaterial", Types.BIGINT},
		{"tituloMaterial", Types.VARCHAR},
		{"fCreacionMaterial", Types.TIMESTAMP},
		{"urlArchMaterial", Types.VARCHAR}, {"descripMaterial", Types.VARCHAR},
		{"T_Ul_PAcademico_id", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idMaterial", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tituloMaterial", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fCreacionMaterial", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("urlArchMaterial", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descripMaterial", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("T_Ul_PAcademico_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AulaVirtual_T_Ul_MaterialEstud (uuid_ VARCHAR(75) null,idMaterial LONG not null primary key,tituloMaterial VARCHAR(75) null,fCreacionMaterial DATE null,urlArchMaterial VARCHAR(75) null,descripMaterial VARCHAR(75) null,T_Ul_PAcademico_id LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AulaVirtual_T_Ul_MaterialEstud";

	public static final String ORDER_BY_JPQL =
		" ORDER BY t_Ul_MaterialEstud.idMaterial ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AulaVirtual_T_Ul_MaterialEstud.idMaterial ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITULOMATERIAL_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDMATERIAL_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static T_Ul_MaterialEstud toModel(T_Ul_MaterialEstudSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		T_Ul_MaterialEstud model = new T_Ul_MaterialEstudImpl();

		model.setUuid(soapModel.getUuid());
		model.setIdMaterial(soapModel.getIdMaterial());
		model.setTituloMaterial(soapModel.getTituloMaterial());
		model.setFCreacionMaterial(soapModel.getFCreacionMaterial());
		model.setUrlArchMaterial(soapModel.getUrlArchMaterial());
		model.setDescripMaterial(soapModel.getDescripMaterial());
		model.setT_Ul_PAcademico_id(soapModel.getT_Ul_PAcademico_id());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<T_Ul_MaterialEstud> toModels(
		T_Ul_MaterialEstudSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<T_Ul_MaterialEstud> models = new ArrayList<T_Ul_MaterialEstud>(
			soapModels.length);

		for (T_Ul_MaterialEstudSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public T_Ul_MaterialEstudModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idMaterial;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdMaterial(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idMaterial;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return T_Ul_MaterialEstud.class;
	}

	@Override
	public String getModelClassName() {
		return T_Ul_MaterialEstud.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<T_Ul_MaterialEstud, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<T_Ul_MaterialEstud, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_MaterialEstud, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((T_Ul_MaterialEstud)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<T_Ul_MaterialEstud, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<T_Ul_MaterialEstud, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(T_Ul_MaterialEstud)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<T_Ul_MaterialEstud, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<T_Ul_MaterialEstud, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<T_Ul_MaterialEstud, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<T_Ul_MaterialEstud, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<T_Ul_MaterialEstud, Object>>();

		attributeGetterFunctions.put("uuid", T_Ul_MaterialEstud::getUuid);
		attributeGetterFunctions.put(
			"idMaterial", T_Ul_MaterialEstud::getIdMaterial);
		attributeGetterFunctions.put(
			"tituloMaterial", T_Ul_MaterialEstud::getTituloMaterial);
		attributeGetterFunctions.put(
			"fCreacionMaterial", T_Ul_MaterialEstud::getFCreacionMaterial);
		attributeGetterFunctions.put(
			"urlArchMaterial", T_Ul_MaterialEstud::getUrlArchMaterial);
		attributeGetterFunctions.put(
			"descripMaterial", T_Ul_MaterialEstud::getDescripMaterial);
		attributeGetterFunctions.put(
			"T_Ul_PAcademico_id", T_Ul_MaterialEstud::getT_Ul_PAcademico_id);
		attributeGetterFunctions.put("groupId", T_Ul_MaterialEstud::getGroupId);
		attributeGetterFunctions.put(
			"companyId", T_Ul_MaterialEstud::getCompanyId);
		attributeGetterFunctions.put("userId", T_Ul_MaterialEstud::getUserId);
		attributeGetterFunctions.put(
			"userName", T_Ul_MaterialEstud::getUserName);
		attributeGetterFunctions.put(
			"createDate", T_Ul_MaterialEstud::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", T_Ul_MaterialEstud::getModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<T_Ul_MaterialEstud, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<T_Ul_MaterialEstud, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<T_Ul_MaterialEstud, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<T_Ul_MaterialEstud, String>)
				T_Ul_MaterialEstud::setUuid);
		attributeSetterBiConsumers.put(
			"idMaterial",
			(BiConsumer<T_Ul_MaterialEstud, Long>)
				T_Ul_MaterialEstud::setIdMaterial);
		attributeSetterBiConsumers.put(
			"tituloMaterial",
			(BiConsumer<T_Ul_MaterialEstud, String>)
				T_Ul_MaterialEstud::setTituloMaterial);
		attributeSetterBiConsumers.put(
			"fCreacionMaterial",
			(BiConsumer<T_Ul_MaterialEstud, Date>)
				T_Ul_MaterialEstud::setFCreacionMaterial);
		attributeSetterBiConsumers.put(
			"urlArchMaterial",
			(BiConsumer<T_Ul_MaterialEstud, String>)
				T_Ul_MaterialEstud::setUrlArchMaterial);
		attributeSetterBiConsumers.put(
			"descripMaterial",
			(BiConsumer<T_Ul_MaterialEstud, String>)
				T_Ul_MaterialEstud::setDescripMaterial);
		attributeSetterBiConsumers.put(
			"T_Ul_PAcademico_id",
			(BiConsumer<T_Ul_MaterialEstud, Long>)
				T_Ul_MaterialEstud::setT_Ul_PAcademico_id);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<T_Ul_MaterialEstud, Long>)
				T_Ul_MaterialEstud::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<T_Ul_MaterialEstud, Long>)
				T_Ul_MaterialEstud::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<T_Ul_MaterialEstud, Long>)
				T_Ul_MaterialEstud::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<T_Ul_MaterialEstud, String>)
				T_Ul_MaterialEstud::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<T_Ul_MaterialEstud, Date>)
				T_Ul_MaterialEstud::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<T_Ul_MaterialEstud, Date>)
				T_Ul_MaterialEstud::setModifiedDate);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getIdMaterial() {
		return _idMaterial;
	}

	@Override
	public void setIdMaterial(long idMaterial) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idMaterial = idMaterial;
	}

	@JSON
	@Override
	public String getTituloMaterial() {
		if (_tituloMaterial == null) {
			return "";
		}
		else {
			return _tituloMaterial;
		}
	}

	@Override
	public void setTituloMaterial(String tituloMaterial) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tituloMaterial = tituloMaterial;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTituloMaterial() {
		return getColumnOriginalValue("tituloMaterial");
	}

	@JSON
	@Override
	public Date getFCreacionMaterial() {
		return _fCreacionMaterial;
	}

	@Override
	public void setFCreacionMaterial(Date fCreacionMaterial) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fCreacionMaterial = fCreacionMaterial;
	}

	@JSON
	@Override
	public String getUrlArchMaterial() {
		if (_urlArchMaterial == null) {
			return "";
		}
		else {
			return _urlArchMaterial;
		}
	}

	@Override
	public void setUrlArchMaterial(String urlArchMaterial) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_urlArchMaterial = urlArchMaterial;
	}

	@JSON
	@Override
	public String getDescripMaterial() {
		if (_descripMaterial == null) {
			return "";
		}
		else {
			return _descripMaterial;
		}
	}

	@Override
	public void setDescripMaterial(String descripMaterial) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descripMaterial = descripMaterial;
	}

	@JSON
	@Override
	public long getT_Ul_PAcademico_id() {
		return _T_Ul_PAcademico_id;
	}

	@Override
	public void setT_Ul_PAcademico_id(long T_Ul_PAcademico_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_T_Ul_PAcademico_id = T_Ul_PAcademico_id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(T_Ul_MaterialEstud.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), T_Ul_MaterialEstud.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public T_Ul_MaterialEstud toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, T_Ul_MaterialEstud>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		T_Ul_MaterialEstudImpl t_Ul_MaterialEstudImpl =
			new T_Ul_MaterialEstudImpl();

		t_Ul_MaterialEstudImpl.setUuid(getUuid());
		t_Ul_MaterialEstudImpl.setIdMaterial(getIdMaterial());
		t_Ul_MaterialEstudImpl.setTituloMaterial(getTituloMaterial());
		t_Ul_MaterialEstudImpl.setFCreacionMaterial(getFCreacionMaterial());
		t_Ul_MaterialEstudImpl.setUrlArchMaterial(getUrlArchMaterial());
		t_Ul_MaterialEstudImpl.setDescripMaterial(getDescripMaterial());
		t_Ul_MaterialEstudImpl.setT_Ul_PAcademico_id(getT_Ul_PAcademico_id());
		t_Ul_MaterialEstudImpl.setGroupId(getGroupId());
		t_Ul_MaterialEstudImpl.setCompanyId(getCompanyId());
		t_Ul_MaterialEstudImpl.setUserId(getUserId());
		t_Ul_MaterialEstudImpl.setUserName(getUserName());
		t_Ul_MaterialEstudImpl.setCreateDate(getCreateDate());
		t_Ul_MaterialEstudImpl.setModifiedDate(getModifiedDate());

		t_Ul_MaterialEstudImpl.resetOriginalValues();

		return t_Ul_MaterialEstudImpl;
	}

	@Override
	public int compareTo(T_Ul_MaterialEstud t_Ul_MaterialEstud) {
		int value = 0;

		if (getIdMaterial() < t_Ul_MaterialEstud.getIdMaterial()) {
			value = -1;
		}
		else if (getIdMaterial() > t_Ul_MaterialEstud.getIdMaterial()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof T_Ul_MaterialEstud)) {
			return false;
		}

		T_Ul_MaterialEstud t_Ul_MaterialEstud = (T_Ul_MaterialEstud)object;

		long primaryKey = t_Ul_MaterialEstud.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<T_Ul_MaterialEstud> toCacheModel() {
		T_Ul_MaterialEstudCacheModel t_Ul_MaterialEstudCacheModel =
			new T_Ul_MaterialEstudCacheModel();

		t_Ul_MaterialEstudCacheModel.uuid = getUuid();

		String uuid = t_Ul_MaterialEstudCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			t_Ul_MaterialEstudCacheModel.uuid = null;
		}

		t_Ul_MaterialEstudCacheModel.idMaterial = getIdMaterial();

		t_Ul_MaterialEstudCacheModel.tituloMaterial = getTituloMaterial();

		String tituloMaterial = t_Ul_MaterialEstudCacheModel.tituloMaterial;

		if ((tituloMaterial != null) && (tituloMaterial.length() == 0)) {
			t_Ul_MaterialEstudCacheModel.tituloMaterial = null;
		}

		Date fCreacionMaterial = getFCreacionMaterial();

		if (fCreacionMaterial != null) {
			t_Ul_MaterialEstudCacheModel.fCreacionMaterial =
				fCreacionMaterial.getTime();
		}
		else {
			t_Ul_MaterialEstudCacheModel.fCreacionMaterial = Long.MIN_VALUE;
		}

		t_Ul_MaterialEstudCacheModel.urlArchMaterial = getUrlArchMaterial();

		String urlArchMaterial = t_Ul_MaterialEstudCacheModel.urlArchMaterial;

		if ((urlArchMaterial != null) && (urlArchMaterial.length() == 0)) {
			t_Ul_MaterialEstudCacheModel.urlArchMaterial = null;
		}

		t_Ul_MaterialEstudCacheModel.descripMaterial = getDescripMaterial();

		String descripMaterial = t_Ul_MaterialEstudCacheModel.descripMaterial;

		if ((descripMaterial != null) && (descripMaterial.length() == 0)) {
			t_Ul_MaterialEstudCacheModel.descripMaterial = null;
		}

		t_Ul_MaterialEstudCacheModel.T_Ul_PAcademico_id =
			getT_Ul_PAcademico_id();

		t_Ul_MaterialEstudCacheModel.groupId = getGroupId();

		t_Ul_MaterialEstudCacheModel.companyId = getCompanyId();

		t_Ul_MaterialEstudCacheModel.userId = getUserId();

		t_Ul_MaterialEstudCacheModel.userName = getUserName();

		String userName = t_Ul_MaterialEstudCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			t_Ul_MaterialEstudCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			t_Ul_MaterialEstudCacheModel.createDate = createDate.getTime();
		}
		else {
			t_Ul_MaterialEstudCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			t_Ul_MaterialEstudCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			t_Ul_MaterialEstudCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return t_Ul_MaterialEstudCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<T_Ul_MaterialEstud, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<T_Ul_MaterialEstud, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_MaterialEstud, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(T_Ul_MaterialEstud)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<T_Ul_MaterialEstud, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<T_Ul_MaterialEstud, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<T_Ul_MaterialEstud, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((T_Ul_MaterialEstud)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, T_Ul_MaterialEstud>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					T_Ul_MaterialEstud.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _idMaterial;
	private String _tituloMaterial;
	private Date _fCreacionMaterial;
	private String _urlArchMaterial;
	private String _descripMaterial;
	private long _T_Ul_PAcademico_id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<T_Ul_MaterialEstud, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((T_Ul_MaterialEstud)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("idMaterial", _idMaterial);
		_columnOriginalValues.put("tituloMaterial", _tituloMaterial);
		_columnOriginalValues.put("fCreacionMaterial", _fCreacionMaterial);
		_columnOriginalValues.put("urlArchMaterial", _urlArchMaterial);
		_columnOriginalValues.put("descripMaterial", _descripMaterial);
		_columnOriginalValues.put("T_Ul_PAcademico_id", _T_Ul_PAcademico_id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("idMaterial", 2L);

		columnBitmasks.put("tituloMaterial", 4L);

		columnBitmasks.put("fCreacionMaterial", 8L);

		columnBitmasks.put("urlArchMaterial", 16L);

		columnBitmasks.put("descripMaterial", 32L);

		columnBitmasks.put("T_Ul_PAcademico_id", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("userName", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private T_Ul_MaterialEstud _escapedModel;

}