/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aula.sb.model.impl;

import com.aula.sb.model.T_Ul_AdminCurso;
import com.aula.sb.service.T_Ul_AdminCursoLocalServiceUtil;

/**
 * The extended model base implementation for the T_Ul_AdminCurso service. Represents a row in the &quot;AulaVirtual_T_Ul_AdminCurso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T_Ul_AdminCursoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see T_Ul_AdminCursoImpl
 * @see T_Ul_AdminCurso
 * @generated
 */
public abstract class T_Ul_AdminCursoBaseImpl
	extends T_Ul_AdminCursoModelImpl implements T_Ul_AdminCurso {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t_ ul_ admin curso model instance should use the <code>T_Ul_AdminCurso</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			T_Ul_AdminCursoLocalServiceUtil.addT_Ul_AdminCurso(this);
		}
		else {
			T_Ul_AdminCursoLocalServiceUtil.updateT_Ul_AdminCurso(this);
		}
	}

}