/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.savvy.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Categoria service. Represents a row in the &quot;Servicio_Savvy_Categoria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savvy.sb.model.impl.CategoriaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savvy.sb.model.impl.CategoriaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Categoria
 * @generated
 */
@ProviderType
public interface CategoriaModel
	extends BaseModel<Categoria>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a categoria model instance should use the {@link Categoria} interface instead.
	 */

	/**
	 * Returns the primary key of this categoria.
	 *
	 * @return the primary key of this categoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this categoria.
	 *
	 * @param primaryKey the primary key of this categoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this categoria.
	 *
	 * @return the uuid of this categoria
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this categoria.
	 *
	 * @param uuid the uuid of this categoria
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the categoria ID of this categoria.
	 *
	 * @return the categoria ID of this categoria
	 */
	public long getCategoriaId();

	/**
	 * Sets the categoria ID of this categoria.
	 *
	 * @param categoriaId the categoria ID of this categoria
	 */
	public void setCategoriaId(long categoriaId);

	/**
	 * Returns the group ID of this categoria.
	 *
	 * @return the group ID of this categoria
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this categoria.
	 *
	 * @param groupId the group ID of this categoria
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this categoria.
	 *
	 * @return the company ID of this categoria
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this categoria.
	 *
	 * @param companyId the company ID of this categoria
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this categoria.
	 *
	 * @return the user ID of this categoria
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this categoria.
	 *
	 * @param userId the user ID of this categoria
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this categoria.
	 *
	 * @return the user uuid of this categoria
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this categoria.
	 *
	 * @param userUuid the user uuid of this categoria
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this categoria.
	 *
	 * @return the user name of this categoria
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this categoria.
	 *
	 * @param userName the user name of this categoria
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this categoria.
	 *
	 * @return the create date of this categoria
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this categoria.
	 *
	 * @param createDate the create date of this categoria
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this categoria.
	 *
	 * @return the modified date of this categoria
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this categoria.
	 *
	 * @param modifiedDate the modified date of this categoria
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre categoria of this categoria.
	 *
	 * @return the nombre categoria of this categoria
	 */
	@AutoEscape
	public String getNombreCategoria();

	/**
	 * Sets the nombre categoria of this categoria.
	 *
	 * @param nombreCategoria the nombre categoria of this categoria
	 */
	public void setNombreCategoria(String nombreCategoria);

	/**
	 * Returns the descripcion of this categoria.
	 *
	 * @return the descripcion of this categoria
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this categoria.
	 *
	 * @param descripcion the descripcion of this categoria
	 */
	public void setDescripcion(String descripcion);

}