/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.savvy.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Etiqueta service. Represents a row in the &quot;Servicio_Savvy_Etiqueta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savvy.sb.model.impl.EtiquetaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savvy.sb.model.impl.EtiquetaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Etiqueta
 * @generated
 */
@ProviderType
public interface EtiquetaModel
	extends BaseModel<Etiqueta>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a etiqueta model instance should use the {@link Etiqueta} interface instead.
	 */

	/**
	 * Returns the primary key of this etiqueta.
	 *
	 * @return the primary key of this etiqueta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this etiqueta.
	 *
	 * @param primaryKey the primary key of this etiqueta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this etiqueta.
	 *
	 * @return the uuid of this etiqueta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this etiqueta.
	 *
	 * @param uuid the uuid of this etiqueta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the etiqueta ID of this etiqueta.
	 *
	 * @return the etiqueta ID of this etiqueta
	 */
	public long getEtiquetaId();

	/**
	 * Sets the etiqueta ID of this etiqueta.
	 *
	 * @param etiquetaId the etiqueta ID of this etiqueta
	 */
	public void setEtiquetaId(long etiquetaId);

	/**
	 * Returns the group ID of this etiqueta.
	 *
	 * @return the group ID of this etiqueta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this etiqueta.
	 *
	 * @param groupId the group ID of this etiqueta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this etiqueta.
	 *
	 * @return the company ID of this etiqueta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this etiqueta.
	 *
	 * @param companyId the company ID of this etiqueta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this etiqueta.
	 *
	 * @return the user ID of this etiqueta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this etiqueta.
	 *
	 * @param userId the user ID of this etiqueta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this etiqueta.
	 *
	 * @return the user uuid of this etiqueta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this etiqueta.
	 *
	 * @param userUuid the user uuid of this etiqueta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this etiqueta.
	 *
	 * @return the user name of this etiqueta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this etiqueta.
	 *
	 * @param userName the user name of this etiqueta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this etiqueta.
	 *
	 * @return the create date of this etiqueta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this etiqueta.
	 *
	 * @param createDate the create date of this etiqueta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this etiqueta.
	 *
	 * @return the modified date of this etiqueta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this etiqueta.
	 *
	 * @param modifiedDate the modified date of this etiqueta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the titulo etiqueta of this etiqueta.
	 *
	 * @return the titulo etiqueta of this etiqueta
	 */
	@AutoEscape
	public String getTituloEtiqueta();

	/**
	 * Sets the titulo etiqueta of this etiqueta.
	 *
	 * @param tituloEtiqueta the titulo etiqueta of this etiqueta
	 */
	public void setTituloEtiqueta(String tituloEtiqueta);

}